const strings = {
  // App
  version: 'Version 1.0',

  //Allergy Screen
  allergyCode: 'Allergy code',
  allergyDescription: 'Allergy description',
  stdAllergenCode: 'Std allergen code',
  startDate: 'Start date',
  inactiveDate: 'Inactive date',

  // Button Strings
  login: 'Login',
  save: 'Save',
  close: 'Close',
  reset: 'Reset',
  edit: 'Edit',
  delete: 'Delete',
  view: 'View',
  select: 'Select',
  update: 'Update',
  discontinue: 'Discontinue',
  add: 'Add',

  // Dashboard Screen
  pastSchedules: 'Past Visit(s)',
  futureSchedules: 'Future Visit(s)',
  fetchingSchedules: 'Fetching your visit(s)',
  noSchedules: 'No visit(s) found!',
  inProgress: 'In Progress',
  completed: 'Completed',

  // Diagnosis Screen
  diagnosisCode: 'Diagnosis code',
  internalDiagnosis: 'Internal diagnosis',
  onsetDate: 'Onset date',
  icd10Code: 'ICD10 code',
  status: 'Status',
  resolvedDate: 'Resolved date',

  // Login Screen
  userName: 'Username',
  password: 'Password',
  poweredBy: 'Powered by',
  cshc: 'CureSelect HealthCare LLP',
  cshcLocation: 'Texas USA',
  cshcSlogan: 'Simple Solution. Better Care.',

  // Medication Screen
  medicationCode: 'Medication code',
  medicationCodeDescription: 'Medication code description',
  instructionInfo: 'Instruction info',
  orderDate: 'Order date',
  takeQuantity: 'Take quantity',
  takeUOM: 'Takke UOM',
  duration: 'Duration',
  durationType: 'Duration type',
  prescriptionStatus: 'Prescription status',
  statusDate: 'Status date',
  attendingDoctor: 'Attending doctor',
  attendingDoctorName: 'Attending doctor name',
  referredBy: 'Referred by',
  referredByName: 'Referred by name',
  medicationId: 'Medication id',
  prescribingClinician: 'Prescribing clinician',
  prescribingClinicianName: 'Prescribing clinician name',

  // MenuDrawer Strings
  allergy: 'Allergy',
  assessment: 'Assessment',
  careTask: 'Care Tasks',
  diagnosis: 'Diagnosis',
  endVisit: 'End Visit',
  medication: 'Medication',
  order: 'Order',
  patientSignature: 'Patient Signature',
  startVisit: 'Start Visit',
  teleconsult: 'Teleconsult',
  visitSummary: 'Visit Summary',
  vitals: 'Vitals',
  updateVisitDocumentStepsToast:
    'Schedule visit document step(s) have been updated successfully!',

  // Medical History Screen
  patientName: 'Patient name',
  smokingStatus: 'Smoking status',
  smokesPerDay: 'Smokes per day',
  smokesDuration: 'Smokes duration',
  stopYear: 'Stop year',
  otherSmokersInFamily: 'Other smokers in family',
  notes: 'Notes',
  alcoholStatus: 'Alcohol status',
  pastMedHist: 'Past medical history',
  familyMedHist: 'Family medical history',

  // Order Strings
  orderId: 'Order id',
  orderCode: 'Order code',
  orderDescription: 'Order description',
  orderInstructionInfo: 'Order / Instruction info',
  orderStatus: 'Order status',
  episodeId: 'Episode id',
  orderingDoctor: 'Ordering doctor',
  orderingDoctorName: 'Ordering doctor name',
  sendOrderTo: 'Send order to',
  contact: 'Contact',
  additionalInformation: 'Additional Information',
  orderingClinician: 'Ordering clinician',
  orderingClinicianName: 'Ordering clinician name',
  otherInformation: 'Other Information',
  inReviewDate: 'In review date',
  cancelReason: 'Cancel reason',

  // Other Strings
  loading: 'Loading',
  finish: 'Finish',
  finished: 'Finished',

  // Patient Details Screen
  fetchingPatientDetails: 'Fetching patient details!',
  language: 'Language',
  mobile: 'Mobile',
  email: 'Email',
  address: 'Address',
  resParty: 'Responsible party',
  emergency: 'Emergency',
  careAddress: 'Care address',
  episodeNo: 'Episode no',
  careType: 'Care type',
  admitDate: 'Admit date',
  admitFrom: 'Admit from',
  admitProblem: 'Admit problem',
  admitNote: 'Admit note',
  location: 'Location',
  episodeManager: 'Episode manager',
  primaryDoctor: 'Primary doctor',
  alternateDoctor: 'Alternate doctor',
  leadPt: 'Lead PT',
  leadOt: 'Lead OT',
  leadSt: 'Lead ST',
  dischargeDate: 'Discharge date',
  carepackCode: 'Carepack code',
  carepackName: 'Carepack name',
  careCode: 'Care code',
  careCodeDescription: 'Care code description',
  scheduleDate: 'Schedule date',
  clinicalResource: 'Clinical resource',
  patientInformation: 'Patient Information',
  episode: 'Episode',
  carePack: 'Care pack',
  notes: 'Notes',
  noAllergy: 'No allergy record(s) found!',
  noDiagnosis: ' No diagnosis record(s) found!',
  noMedication: 'No medication record(s) found!',
  noOrder: 'No order record(s) found!',
  next2Schedules: "Next 2 schedule's",

  // ScanDocs Strings
  buildingScanDocsForm: 'Building scan document form!',
  docCategory: 'Document category',
  fileType: 'File type',
  uploadDocument: 'Upload document',
  noFileChosen: 'No file chosen',

  // Schedule Strings
  schedule: 'Visit',
  scanDocs: 'Scan Docs',
  dateTime: 'Date & Time',
  geoCodeStatus: 'Geo Code Status',
  updateStartVisit: 'Update / Start Visit',
  updateEndVisit: 'Update / End Visit',
  startVisitToast: 'Start Visit has been updated successfully!',
  endVisitToast: 'End Visit has been updated successfully!',

  // Schedule Card Strings
  patientDetails: 'Patient details',
  visitHeader: 'Visit header',
  medicalHistory: 'Medical history',

  // ShowAll Strings
  statusFlags: 'Status Flag(s)',
  standardAllergenCode: 'Standard allergen code',
  permissinDenied: "Sorry! You don't have the permission!",
  doctorName: 'Doctor name',
  orderTo: 'Order to',
  orderInfo: 'Order info',
  newDate: 'New date',
  reviewDate: 'Review date',
  cancelledDate: 'Cancelled date',
  prescribedDate: 'Prescribed date',
  discontinuedDate: 'Discontinued date',

  // Visit Header Strings
  fetchingVisitHeaderDetails: 'Fetching visit header details!',
  roomNumber: 'Room number',
  bedNumber: 'Bed number',
  city: 'City',
  phone: 'Phone',
  carePackInformation: 'Care Pack Information',
  docType: 'Doc type',
  scheduleInformation: 'Schedule Information',
  scheduleTime: 'Schedule time',
  scheduleDuration: 'Schedule duration',
  scheduleTimeSlot: 'Schedule time slot',
  scheduleStatus: 'Schedule status',

  // Vitals Strings
  buildingVitalsForm: 'Building vitals form!',
  date: 'Date',
  time: 'Time',
  method: 'Method',
  temperature: 'Temperature',
  height: 'Height',
  weight: 'Weight',
  bloodPressureSystolic: 'BP systolic',
  bloodPressureDiastolic: 'BP diastolic',
  pulse: 'Pulse',
  respirations: 'Respirations',
  bloodGlucose: 'Blood glucose',
  oxygenLevel: 'O₂ level',
  oxygenSaturation: 'O₂ saturation',
  painScale: 'Pain scale',
  painScaleHint:
    'Hint: 0-No Pain, 1-3 Minor Pain, 4-6 Moderate Pain & 7-10 Severe Pain.',
  painLocation: 'Pain location',
  painNotes: 'Pain notes',
  painDecreaseActivity: 'Pain decrease activity',
  painIncreaseActivity: 'Pain increase activity',

  // Error Strings
  userNameError: "Username can't be empty!",
  passwordError: "Password can't be empty!",
  invalidTimeError: 'Please! Check the time!',
  allergyCodeError: "Allergy code can't be empty!",
  allergyDescriptionError: "Allergy description can't be empty!",
  statusError: "Status can't be empty!",
  invalidDates: 'Please! Check the selected dates!',
  diagnosisCodeError: "Diagnosis code can't be empty!",
  internalDiagnosisError: "Internal diagnosis can't be empty!",
  medicationCodeError: "Medication code can't be empty!",
  mediationDescriptionError: "Medication description can't be empty!",
  prescriptionStatusError: "Prescription status can't be empty!",
  attendingDoctorError: "Attending doctor error can't be empty!",
  orderDateError: "Order date can't be empty!",
  visitSummaryError: "Visit summary can't be empty!",
  orderCodeError: "Order code can't be empty!",
  orderDescriptionError: "Order description can't be empty!",
  orderStatusError: "Order status can't be empty!",
  orderingDoctorError: "Ordering doctor can't be empty!",
  orderCodeOrderDescriptionError:
    "Order code and Order description can't be empty!",
  smokingStatusError: "Smoking status can't be empty!",
  smokesPerDayError: "Smokes per day can't be empty!",
  smokesDurationError: "Smokes duration can't empty!",
  alcoholStatusError: "Alcohol status can't be empty!",
  pastMedHistError: "Past medical history can't be empty!",
  smokesDurationtError:
    "Smokes duration can't be empty unless patient is not a Smoker!",
  smokesPerDaytError:
    "Smokes per day can't be empty unless patient is not a Smoker!",
  sendOrderToError: "Send order to can't be empty!",
  fileUploadError: 'Choose atleast one file to upload!',
  fileTypeError: 'File format must be in jpg/jpeg/png/pdf/doc/docx!',
  fileSizeError: 'File size must be less than 5 MB!',
  documentCategoryError: "Document category can't be empty!",
  fileCategoryError: "File type can't be empty!",
};

export default strings;
